In [1]:
# https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ

In [2]:
!wget https://raw.githubusercontent.com/karpathy/makemore/refs/heads/master/names.txt

--2024-12-28 15:22:56--  https://raw.githubusercontent.com/karpathy/makemore/refs/heads/master/names.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 228145 (223K) [text/plain]
Saving to: ‘names.txt’

names.txt           100%[===================>] 222.80K  --.-KB/s    in 0.01s   

2024-12-28 15:22:56 (18.8 MB/s) - ‘names.txt’ saved [228145/228145]



In [3]:
# NeuralNet
# recieve single char as input and return prob distrubition for next char

In [4]:
words = open("names.txt", "r").read().splitlines()

In [5]:
chars = sorted(list(set(''.join(words))))

In [6]:
stoi = {s:(i+1) for i,s in enumerate(chars)}
# use "." as special char instead of <S> or <E>
stoi['.'] = 0

In [7]:
import torch

In [8]:
# create training set
xs, ys = [], []

for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    xs.append(ix1)
    ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [9]:
xs

tensor([ 0,  5, 13,  ..., 25, 26, 24])

In [10]:
ys

tensor([ 5, 13, 13,  ..., 26, 24,  0])

In [11]:
# one hot encode chars

In [12]:
import torch.nn.functional as F
# we converted one hot to float casue we want to always feed float to neural net not ints
# one_hot always gives 
xenc = F.one_hot(xs, num_classes=27).float()

In [13]:
xenc

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 1., 0., 0.]])

In [14]:
# weights of neuron
W = torch.randn((27,1))
W

tensor([[-0.0640],
        [-2.2173],
        [-0.3049],
        [ 1.6955],
        [-0.9975],
        [-1.0374],
        [-1.0391],
        [ 1.2023],
        [-1.1747],
        [ 0.0551],
        [ 0.3540],
        [ 0.4848],
        [-0.6099],
        [ 0.2918],
        [-0.5877],
        [ 1.1309],
        [ 1.2196],
        [ 0.8115],
        [-1.2961],
        [-0.9029],
        [-0.2112],
        [-0.0150],
        [ 1.0249],
        [ 0.7807],
        [ 0.8420],
        [ 2.4781],
        [-0.9460]])

In [15]:
# @ means matrix multiplication
xenc @ W

tensor([[-0.0640],
        [-1.0374],
        [ 0.2918],
        ...,
        [ 2.4781],
        [-0.9460],
        [ 0.8420]])

In [16]:
# weights of 27 neuron
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27,27), requires_grad=True, generator=g)
W

tensor([[ 1.5674e+00, -2.3729e-01, -2.7385e-02, -1.1008e+00,  2.8588e-01,
         -2.9643e-02, -1.5471e+00,  6.0489e-01,  7.9136e-02,  9.0462e-01,
         -4.7125e-01,  7.8682e-01, -3.2843e-01, -4.3297e-01,  1.3729e+00,
          2.9334e+00,  1.5618e+00, -1.6261e+00,  6.7716e-01, -8.4039e-01,
          9.8488e-01, -1.4837e-01, -1.4795e+00,  4.4830e-01, -7.0730e-02,
          2.4968e+00,  2.4448e+00],
        [-6.7006e-01, -1.2199e+00,  3.0314e-01, -1.0725e+00,  7.2762e-01,
          5.1114e-02,  1.3095e+00, -8.0220e-01, -8.5042e-01, -1.8068e+00,
          1.2523e+00, -1.2256e+00,  1.2165e+00, -9.6478e-01, -2.3211e-01,
         -3.4762e-01,  3.3244e-01, -1.3263e+00,  1.1224e+00,  5.9641e-01,
          4.5846e-01,  5.4011e-02, -1.7400e+00,  1.1560e-01,  8.0319e-01,
          5.4108e-01, -1.1646e+00],
        [ 1.4756e-01, -1.0006e+00,  3.8012e-01,  4.7328e-01, -9.1027e-01,
         -7.8305e-01,  1.3506e-01, -2.1161e-01, -1.0406e+00, -1.5367e+00,
          9.3743e-01, -8.8303e-01,  1.74

In [17]:
xenc @ W

tensor([[ 1.5674, -0.2373, -0.0274,  ..., -0.0707,  2.4968,  2.4448],
        [ 0.4724,  1.4830,  0.3175,  ..., -0.4275, -2.1259,  0.9604],
        [ 0.1936,  1.0532,  0.6339,  ...,  1.5447,  0.6006, -0.7091],
        ...,
        [ 0.7414, -0.5879, -0.4651,  ..., -0.1388,  1.3096, -0.2580],
        [ 1.0669,  0.2136, -0.7660,  ...,  1.3405, -0.2175,  0.8627],
        [ 0.2163, -0.7873, -0.3301,  ..., -0.2630, -0.7552,  0.8191]],
       grad_fn=<MmBackward0>)

In [18]:
# assume neural network gives log counts, we exponentiate them to get actual count
logits = (xenc @ W) # log counts
counts = logits.exp()
counts

tensor([[ 4.7940,  0.7888,  0.9730,  ...,  0.9317, 12.1434, 11.5281],
        [ 1.6038,  4.4060,  1.3737,  ...,  0.6521,  0.1193,  2.6128],
        [ 1.2136,  2.8669,  1.8850,  ...,  4.6866,  1.8232,  0.4921],
        ...,
        [ 2.0989,  0.5555,  0.6281,  ...,  0.8704,  3.7049,  0.7726],
        [ 2.9062,  1.2382,  0.4649,  ...,  3.8208,  0.8046,  2.3696],
        [ 1.2415,  0.4551,  0.7189,  ...,  0.7687,  0.4699,  2.2685]],
       grad_fn=<ExpBackward0>)

In [19]:
# prob is count normalized
probs = counts / counts.sum(1, keepdims=True)
probs

tensor([[0.0607, 0.0100, 0.0123,  ..., 0.0118, 0.1537, 0.1459],
        [0.0290, 0.0796, 0.0248,  ..., 0.0118, 0.0022, 0.0472],
        [0.0312, 0.0737, 0.0484,  ..., 0.1204, 0.0469, 0.0126],
        ...,
        [0.0301, 0.0080, 0.0090,  ..., 0.0125, 0.0531, 0.0111],
        [0.0634, 0.0270, 0.0101,  ..., 0.0833, 0.0175, 0.0517],
        [0.0308, 0.0113, 0.0178,  ..., 0.0190, 0.0116, 0.0562]],
       grad_fn=<DivBackward0>)

In [20]:
# we can get prob directly from logits using softmax func
# then no need of doing exp and normalization urself

In [21]:
# gradient descent

In [22]:
torch.arange(len(xs))

tensor([     0,      1,      2,  ..., 228143, 228144, 228145])

In [23]:
# loss function
# negative log likelihood
loss = -probs[torch.arange(len(xs)), ys].log().mean()

In [24]:
loss

tensor(3.7590, grad_fn=<NegBackward0>)

In [25]:
# backward pass
# set grad to zero/none
W.grad = None

loss.backward()

In [26]:
W.grad

tensor([[ 8.5187e-03, -1.7928e-02, -3.9954e-03, -6.1678e-03, -5.0425e-03,
         -4.9855e-03, -1.4495e-03,  3.2138e-04, -1.9076e-03,  1.8004e-03,
         -9.5068e-03, -9.0844e-03, -5.6108e-03, -9.9719e-03,  1.9904e-03,
          3.1664e-02,  6.2140e-03, -5.3713e-05, -3.6864e-03, -8.2406e-03,
         -9.7537e-04,  1.1901e-03, -1.2434e-03,  1.4365e-03,  1.0683e-03,
          1.9233e-02,  1.6413e-02],
        [-2.6880e-02, -1.1534e-03,  3.5157e-03, -5.7258e-04,  4.4327e-03,
          1.5423e-03,  1.5517e-02,  1.2128e-03, -8.3641e-03, -6.5184e-03,
          1.4442e-02, -1.2133e-03,  3.5937e-03, -5.5054e-03, -2.0389e-02,
          2.7948e-03,  5.7026e-03,  8.9113e-04, -9.4968e-04,  2.9929e-03,
          3.8649e-03,  2.9188e-03, -2.8925e-03,  4.1746e-03,  8.9087e-03,
         -1.5171e-03, -5.5008e-04],
        [-2.1135e-04, -1.3155e-03,  1.9726e-04,  3.9496e-04, -1.8479e-04,
         -2.7573e-03,  2.8475e-04,  2.0133e-04, -9.1831e-05, -8.9764e-04,
          6.3084e-04,  1.0287e-04,  9.73

In [27]:
# update weights
W.data += -0.1 * W.grad

In [28]:
# now do it in loop
for k in range(100):
    # forward pass
    xenc = F.one_hot(xs, num_classes=27).float()
    # cause xenc is one hot encoded
    # logits will just select that row of W
    logits = xenc @ W
    counts = logits.exp()
    probs = counts / counts.sum(1, keepdims=True)
    loss = -probs[torch.arange(len(xenc)), ys].log().mean()
    print(loss.item())

    # backward pass
    W.grad = None
    loss.backward()

    # update
    W.data += -50 * W.grad

3.758039712905884
3.370584011077881
3.1537325382232666
3.02016544342041
2.9275617599487305
2.8602912425994873
2.809643268585205
2.770033836364746
2.7380166053771973
2.711449146270752
2.688962697982788
2.6696534156799316
2.652899742126465
2.6382505893707275
2.625364303588867
2.6139698028564453
2.60384464263916
2.5948050022125244
2.5866966247558594
2.579390048980713
2.5727767944335938
2.566765069961548
2.5612776279449463
2.5562491416931152
2.5516247749328613
2.5473577976226807
2.543407678604126
2.5397415161132812
2.536329746246338
2.5331482887268066
2.530174970626831
2.5273914337158203
2.5247812271118164
2.5223300457000732
2.520024538040161
2.5178537368774414
2.5158066749572754
2.5138742923736572
2.5120487213134766
2.5103206634521484
2.508683919906616
2.507131576538086
2.5056586265563965
2.504258394241333
2.502926826477051
2.5016584396362305
2.5004498958587646
2.4992966651916504
2.4981954097747803
2.497142791748047
2.496135950088501
2.4951717853546143
2.4942476749420166
2.493361711502075

In [29]:
# we can have model smoothing in Neural net also
# if we force our weights to be near 0 or same to each other
# then our probibility will be more uniform
# and this is called normalization

In [30]:
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [31]:
# generate names
g = torch.Generator().manual_seed(2147483647)

# generate 5 names
for i in range(5):
    out = []
    # start with start char
    ix = 0
    while True:
        # run neural net on each char
        xenc = F.one_hot(torch.tensor([ix]), num_classes=27).float()
        logits = xenc @ W
        counts = logits.exp()
        p = counts / counts.sum(1, keepdims=True)

        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out.append(itos[ix])
        if ix == 0:
            break
    print(''.join(out))

junide.
janasah.
p.
cfay.
a.
